### ISSUE TITLE
Cannot read properties of undefined (reading 'getUserMedia')

### ISSUE THREAD

**Issue by furqan72672** [samhirtarif/react-audio-recorder#37] opened 2023-05-12 15:10 UTC
this error is occurring with the build, it is running fine in local environment.
  "build": "vite build",
  "vite": "^3.2.4"

**Comment by samhirtarif** [comment] 2023-05-12 17:37
Could you please share the piece of code where you're using the package?
Also, which device and OS are you using?

**Comment by samhirtarif** [comment] 2023-05-12 18:05
@furqan72672 - Since you've mentioned the use of build, I am assuming you're trying to serve it over the network.
In that case, if you are serving over http, `navigator.mediaDevices` will be `undefined` as per the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#security)

![image](https://github.com/samhirtarif/react-audio-recorder/assets/89391183/514b565f-442c-4e31-8768-bd560ac80ace)

This was the only case I was able to reproduce this and I have tired windows, macOS, android and iOS. If this isn't the case, please do share a code snippet, so I can take dig deeper. Otherwise, I believe we can close this issue

**Comment by samhirtarif** [comment] 2023-05-12 18:35
@furqan72672 - Since you've mentioned the use of build, I am assuming you're trying to serve it over the network.
In that case, if you are serving over http, `navigator.mediaDevices` will be `undefined` as per the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#security)

![image](https://github.com/samhirtarif/react-audio-recorder/assets/89391183/514b565f-442c-4e31-8768-bd560ac80ace)

This was the only way I was able to reproduce this issue and I have tired on Windows, macOS, android and iOS.

I am marking this issue closed for now. If this isn't the scenario you're facing please feel free to re-open the issue with further details and a code snippet of how you're using the package.

**Closed by samhirtarif** 2023-05-12 18:35 UTC

**Comment by furqan72672** [comment] 2023-05-13 09:35
Thank you for enlightening me. Reading your answer, I think it is a http issue and you are right
